GET http://127.0.0.1:4000
###
POST http://127.0.0.1:4000
Content-Type: application/json

{
    "name": "Budi",
    "email": "budi@mail.com"
}
###
DELETE http://127.0.0.1:4000/Budi

###
PUT http://127.0.0.1:4000
Content-Type: application/json

{
    "name": "Yasha Comp",
    "email": "yasha@mail.com"
}